-- Run in Supabase SQL Editor
create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  owner_name text not null default 'প্রোঃ খলিলুর রহমান',
  phone1 text not null default '01881-246230',
  phone2 text not null default '01787-117759',
  address text not null default 'আমরাইদ বাজার, কাপাসিয়া রোড, পেট্রোল পাম্পের দক্ষিণ পাশে, স-মিল সংলগ্ন, কাপাসিয়া, গাজীপুর।',
  updated_at timestamptz not null default now()
);
insert into public.site_settings (id) values (1) on conflict (id) do nothing;
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text not null default 'আমাদের কাজ',
  created_at timestamptz not null default now()
);
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.site_settings enable row level security;
alter table public.gallery enable row level security;
alter table public.admin_users enable row level security;
drop policy if exists "Public can read settings" on public.site_settings;
create policy "Public can read settings" on public.site_settings for select using (true);
drop policy if exists "Admins can update settings" on public.site_settings;
create policy "Admins can update settings" on public.site_settings for update to authenticated using (exists(select 1 from public.admin_users a where a.user_id = auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id = auth.uid()));
drop policy if exists "Public can read gallery" on public.gallery;
create policy "Public can read gallery" on public.gallery for select using (true);
drop policy if exists "Admins can manage gallery" on public.gallery;
create policy "Admins can manage gallery" on public.gallery for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id = auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id = auth.uid()));
-- Create a PUBLIC storage bucket named cnc-gallery in Dashboard > Storage.
-- Storage policies:
drop policy if exists "Public can view cnc gallery" on storage.objects;
create policy "Public can view cnc gallery" on storage.objects for select using (bucket_id = 'cnc-gallery');
drop policy if exists "Admins upload cnc gallery" on storage.objects;
create policy "Admins upload cnc gallery" on storage.objects for insert to authenticated with check (bucket_id = 'cnc-gallery' and exists(select 1 from public.admin_users a where a.user_id = auth.uid()));
drop policy if exists "Admins delete cnc gallery" on storage.objects;
create policy "Admins delete cnc gallery" on storage.objects for delete to authenticated using (bucket_id = 'cnc-gallery' and exists(select 1 from public.admin_users a where a.user_id = auth.uid()));
drop policy if exists "Admins can verify own admin row" on public.admin_users;
create policy "Admins can verify own admin row" on public.admin_users for select to authenticated using (user_id = auth.uid());
